# use epsilon greedy action selector
action_selector: "opt_selector"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 1000000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "opt_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

central_loss: 1
qmix_loss: 1

central_mixing_embed_dim: 256
central_action_embed: 1
central_mac: "basic_central_mac"
central_agent: "central_rnn"
central_rnn_hidden_dim: 64
central_mixer: "ff"

name: "opt_qmix"
mac: "opt_mac"
w: 0.5
normal_start: 1.0
normal_finish: 0
normal_anneal_time: 50000

use_temp_norm: True
use_norm: True
sum_opt: True
normalmax: 1
use_state: True
use_internal: False
